#!/usr/bin/env python3
"""
Publish per-tool next reservation MQTT messages from downloaded JSON datasets.

Inputs (generated by vm-server/API/scripts/*):
  - vm-server/API/data/reservations_recent.json  (payload["rows"])
  - vm-server/API/data/users_lookup.json         (payload["users"])
  - vm-server/API/data/tools_lookup.json         (payload["tools"])

Allow-list:
  - vm-server/mqtt_reservation_tools.yaml (or MQTT_RESERVATION_TOOLS_FILE override)

Publishes (retained, QoS 1) one topic per tool:
  - {MQTT_TOPIC_PREFIX}/{tool_id}/next_reservation
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

import paho.mqtt.client as mqtt

from config_parser import get_mqtt_broker, get_esp32_port, get_topic_prefix_str, load_config_env
from nemo_helpers import pick_next_reservation_for_tool
from reservation_allowlist import load_allowed_tool_ids


_VM_SERVER_DIR = Path(__file__).resolve().parent


def _env_int(name: str, default: int) -> int:
    raw = (os.getenv(name) or "").strip()
    if not raw:
        return default
    try:
        return int(raw)
    except ValueError:
        return default


def _default_allowlist_path() -> Path:
    raw = (os.getenv("MQTT_RESERVATION_TOOLS_FILE") or "").strip().strip('"').strip("'")
    if raw:
        p = Path(raw).expanduser()
        return p.resolve() if p.is_absolute() else (_VM_SERVER_DIR / p).resolve()
    return (_VM_SERVER_DIR / "mqtt_reservation_tools.yaml").resolve()


def _default_data_path(name: str) -> Path:
    return (_VM_SERVER_DIR / "API" / "data" / name).resolve()


def _load_json(path: Path) -> Any:
    raw = path.read_text(encoding="utf-8")
    return json.loads(raw)


def _load_lookup_map(path: Path, key: str, logger: logging.Logger) -> Dict[int, str]:
    """
    Read {"<key>": {"<id_str>": "<display>"}} and convert keys to int.
    Returns {} if file missing or malformed.
    """
    if not path.is_file():
        logger.error("Missing required lookup file: %s", path)
        return {}
    try:
        data = _load_json(path)
    except Exception as e:
        logger.exception("Failed to read JSON %s: %s", path, e)
        return {}

    if not isinstance(data, dict):
        logger.error("Unexpected JSON shape in %s (expected object)", path)
        return {}
    raw_map = data.get(key)
    if not isinstance(raw_map, dict):
        logger.error("Unexpected JSON shape in %s (missing %r map)", path, key)
        return {}

    out: Dict[int, str] = {}
    for k, v in raw_map.items():
        try:
            ik = int(k)
        except (TypeError, ValueError):
            continue
        if isinstance(v, str):
            out[ik] = v.strip()
    return out


def _load_reservation_rows(path: Path, logger: logging.Logger) -> List[Any]:
    if not path.is_file():
        logger.error("Missing required reservations file: %s", path)
        return []
    try:
        data = _load_json(path)
    except Exception as e:
        logger.exception("Failed to read JSON %s: %s", path, e)
        return []
    if not isinstance(data, dict):
        logger.error("Unexpected JSON shape in %s (expected object)", path)
        return []
    rows = data.get("rows")
    if not isinstance(rows, list):
        logger.error("Unexpected JSON shape in %s (expected payload['rows'] list)", path)
        return []
    return rows


def _configure_logger() -> logging.Logger:
    level_name = (os.getenv("LOG_LEVEL") or "INFO").strip().upper()
    level = getattr(logging, level_name, logging.INFO)
    logging.basicConfig(level=level, format="%(asctime)s - %(levelname)s - %(message)s")
    return logging.getLogger("publish_next_reservations_from_files")


def _mqtt_client(logger: logging.Logger) -> mqtt.Client:
    client = mqtt.Client(client_id=f"nemo-next-reservation-publisher-{os.getpid()}")
    user = (os.getenv("MQTT_USERNAME") or "").strip()
    pwd = (os.getenv("MQTT_PASSWORD") or "").strip()
    if user and pwd:
        client.username_pw_set(user, pwd)

    def _on_connect(_client, _userdata, _flags, rc):
        if rc == 0:
            logger.info("✅ Connected to MQTT broker for publish")
        else:
            logger.error("❌ MQTT connect failed rc=%s (%s)", rc, mqtt.error_string(rc))

    def _on_disconnect(_client, _userdata, rc):
        if rc != 0:
            logger.warning("⚠️ MQTT disconnected rc=%s (%s)", rc, mqtt.error_string(rc))

    client.on_connect = _on_connect
    client.on_disconnect = _on_disconnect
    return client


def main(argv: Optional[List[str]] = None) -> int:
    load_config_env()
    logger = _configure_logger()

    ap = argparse.ArgumentParser()
    ap.add_argument("--reservations", default=str(_default_data_path("reservations_recent.json")))
    ap.add_argument("--users", default=str(_default_data_path("users_lookup.json")))
    ap.add_argument("--tools", default=str(_default_data_path("tools_lookup.json")))
    ap.add_argument("--allowlist", default=str(_default_allowlist_path()))
    ap.add_argument("--dry-run", action="store_true", help="Build payloads but do not publish.")
    args = ap.parse_args(argv)

    reservations_path = Path(args.reservations).expanduser().resolve()
    users_path = Path(args.users).expanduser().resolve()
    tools_path = Path(args.tools).expanduser().resolve()
    allow_path = Path(args.allowlist).expanduser().resolve()

    tz_offset_hours = _env_int("TIMEZONE_OFFSET_HOURS", -7)
    lookahead_days = _env_int("NEMO_RESERVATIONS_LOOKAHEAD_DAYS", 7)
    prefix = get_topic_prefix_str()

    reservations = _load_reservation_rows(reservations_path, logger)
    if not reservations:
        return 2

    user_map = _load_lookup_map(users_path, "users", logger)
    if not user_map:
        return 2

    tools_map = _load_lookup_map(tools_path, "tools", logger)
    if not tools_map:
        return 2

    allow_ids = load_allowed_tool_ids(allow_path, logger)
    if not allow_ids:
        logger.warning("No allow-listed tool IDs (file: %s). Nothing to publish.", allow_path)
        return 0

    broker = get_mqtt_broker()
    port = get_esp32_port()
    logger.info("MQTT publish target mqtt://%s:%s prefix=%s tools=%s", broker, port, prefix, len(allow_ids))
    logger.info(
        "Inputs reservations=%s users=%s tools=%s allowlist=%s",
        reservations_path,
        users_path,
        tools_path,
        allow_path,
    )

    payloads: Dict[int, str] = {}
    for tool_id in allow_ids:
        tool_name = tools_map.get(int(tool_id), f"Tool {tool_id}")
        payload_obj = pick_next_reservation_for_tool(
            reservations,
            int(tool_id),
            int(lookahead_days),
            int(tz_offset_hours),
            dict(user_map),
            tool_name,
        )
        payloads[int(tool_id)] = json.dumps(payload_obj, ensure_ascii=False)

    if args.dry_run:
        logger.info("Dry-run: built %s payloads; skipping publish.", len(payloads))
        return 0

    client = _mqtt_client(logger)
    try:
        client.connect(broker, port, keepalive=60)
    except Exception as e:
        logger.exception("Failed to connect to mqtt://%s:%s : %s", broker, port, e)
        return 2
    client.loop_start()

    try:
        ok = 0
        for tool_id, body in payloads.items():
            topic = f"{prefix}/{tool_id}/next_reservation"
            res = client.publish(topic, body, qos=1, retain=True)
            if res.rc == mqtt.MQTT_ERR_SUCCESS:
                ok += 1
            else:
                logger.error(
                    "Publish failed tool_id=%s rc=%s (%s) topic=%s",
                    tool_id,
                    res.rc,
                    mqtt.error_string(res.rc),
                    topic,
                )
        logger.info("Published next_reservation: ok=%s total=%s", ok, len(payloads))
        return 0 if ok == len(payloads) else 3
    finally:
        try:
            client.loop_stop()
        except Exception:
            pass
        try:
            client.disconnect()
        except Exception:
            pass


if __name__ == "__main__":
    raise SystemExit(main())

